---
- name: install web server
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      apt: 
        name: nginx
        state: lastest
        update_cache: True
      notify:
        - Start Nginx
  handler: 
    - name: start Nginx
      service:
        name: nginx
        state: started
